# Generated by Django 4.2.7 on 2023-11-29 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('valido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoSala', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsavelSala',
            fields=[
                ('participante_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='amigoSecreto.participante')),
                ('senha', models.CharField(max_length=32)),
            ],
            bases=('amigoSecreto.participante',),
        ),
        migrations.CreateModel(
            name='SalaSorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataSorteio', models.DateField()),
                ('valorMaximoPresente', models.FloatField(default=0.0)),
                ('situacao', models.BooleanField(default=True)),
                ('salaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigoSecreto.sala')),
            ],
        ),
        migrations.AddField(
            model_name='sala',
            name='responsavelSala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigoSecreto.responsavelsala'),
        ),
    ]
