# Generated by Django 4.2.7 on 2023-11-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigoSecreto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='responsavelSala',
            new_name='participante',
        ),
        migrations.AddField(
            model_name='sala',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
