# Generated by Django 4.2.7 on 2023-12-05 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amigoSecreto', '0002_alter_salasorteio_codigosala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaparticipante',
            name='codigoSala',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amigoSecreto.sala'),
        ),
    ]
