# Generated by Django 4.2.7 on 2023-11-29 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amigoSecreto', '0002_rename_responsavelsala_sala_participante_sala_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='participante',
            new_name='responsavelSala',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='admin',
        ),
        migrations.CreateModel(
            name='SalaParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoSala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigoSecreto.sala')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigoSecreto.participante')),
            ],
        ),
    ]
