# Generated by Django 4.2.7 on 2023-12-05 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amigoSecreto', '0003_alter_salaparticipante_codigosala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='codigoSala',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='salaparticipante',
            name='codigoSala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigoSecreto.sala'),
        ),
    ]
