# Generated by Django 4.2.7 on 2023-11-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigoSecreto', '0003_rename_participante_sala_responsavelsala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='valido',
        ),
        migrations.AddField(
            model_name='salaparticipante',
            name='valido',
            field=models.BooleanField(default=False),
        ),
    ]
