# Generated by Django 4.2.7 on 2023-11-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amigoSecreto', '0004_remove_participante_valido_salaparticipante_valido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salasorteio',
            old_name='salaId',
            new_name='codigoSala',
        ),
    ]
