# Generated by Django 4.2.7 on 2023-11-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amigoSecreto', '0005_rename_salaid_salasorteio_codigosala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaparticipante',
            old_name='participante',
            new_name='email',
        ),
    ]
